language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm install
- echo "$NPM_SECRET" >> ~/.npmrc
- npm test
after_script: greenkeeper-lockfile-upload
deploy:
  provider: script
  script: npm publish
  on:
    tags: true
    repo: laundree/sdk
env:
  global:
  - secure: RxazIPoDrgToNpLB8oYOxatogmu6fzk6rBVsrOlHI1agJTmMj/fzqZRtaKku+xOFxqOpWkO+ZBzbcRmgO60MMcXHSyAySIqIKiEICckhs2YnhEJLqFV6IzsRSOclVzdWB98NYgFUmd5z0cOtR83n0jGObnntFTrBrJJX475Ju/EvFPx/OIxINpKqXHNt8BL4jjt58htxxTYEh8E95HIJM2WBO/iXyqpaQxAMqX2z9Q0U4TFN48/VPsFA2+YCOOW3rTAVwRx+BJHLVj0JYHVjYUezkvwPkeQXTzbesgTbLtMIhMqk2acUGS7WjoVQKbDazn0vo6x+R7Fk+GGzREA8O3xu77LOz8pMuCPRMKuA2ZekBiv95+/Pi6zNHj6ou42NVSooqkEP30aHfA1SHerIHy5C1Uv4uzLxVn9uzn5tEHUkpmhKeBUTCTnrJXXXPQId2VdT0244XUkKcVGqagXXM9Y9c47DtjZghz46JDGqeyVo84TLLODvkAuhkZt5SuGFdOW3XRIDsJ3o1aQLSRS9ciw1dOg9Ol3jemMNn3rw1BqouB36NKv2hDnS4MRU6KHAngKEYiTyn3odaGy8yRP0MCAZDyC3TkBrONRbA0107u+KGY47OabbHrYAUL54Af1seO12zHBlv7JvIAeqfrSjlVBKBCDmj3eEcO0DhlVmS8c=
  - secure: SeiSWMzoWhkcThgNazeYEg9Mf9xGLekLgFY6yl+aDlijqV/sUrErPB2Xv3oW24+huTFQpNVjKALrbXtCz+kAzNgwE0JoVqENnJ/1B7vB+61l01dXf6Qkmks1q6Rx5IDHWk4F1hl15j/81aq04VSuHX08V5yI6nkLCCrXay5YbAoD/DAydiXG+9D0foYZZnA3+UnFRQNP/aPu3MVGI0Jazeql/pGyUGFsKdSbK51MeNDC7iLHpBH3QIflfSST3IZFJDZ11TVVmiHcKWYw7bkolYEsEpXO2DfcwetPu7HVSq6mOoOoMDvOb6qQQhPcg6IkuiqbMbslfDyR93EnhNE+lSvbU7Cq7afp1Uyb2LdrsBMOewx4B4sHNqyxeEamUGtG2uD9CHrgK4xW0twPYMhD0B861lrVMIVXu+yy4JpsYhS6e3jwUXwWv06y+I7oplamg17PhdP22AuhdThz4oU919miJx+Q6SEhGhrvGxhW7rBY2GSWsEGwuzTDCHWv8KaQycYSlFh5WaaSrSv8LB6HT4fuVl7hKMxciGm1hInsH9GaFN/28XSlz8R5XKt5LhIhSS9a1ur8LRFY4xCcjunQyAXQKZAA/UI0MujtCo8bMrHojfENQYE8sOx6jTglkMJFf5mRWcrYg5N/b5dZckHV0oKA+RXPRhlvVjaB1woLfSs=
